# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MusicTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import random,time
from pygame import mixer
from mutagen.mp3 import MP3
from PyQt5 import QtCore, QtGui, QtWidgets
import source_rc
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *



mixer.init()
musiclist=[]
play = False
current_song = None
count = 0
songLength = 0
index = 0

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("background-color: rgb(17,17,17);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NotificationPanel = QtWidgets.QLabel(self.centralwidget)
        self.NotificationPanel.setGeometry(QtCore.QRect(0, 0, 1280, 70))
        self.NotificationPanel.setStyleSheet("background: transparent;\n"
"border-bottom:2px solid rgb(255, 255, 255);")
        self.NotificationPanel.setObjectName("NotificationPanel")
        self.TimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeLabel.setGeometry(QtCore.QRect(10, 16, 160, 38))
        self.TimeLabel.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"color: rgb(255, 255, 255);\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 30px;")
        self.TimeLabel.setObjectName("TimeLabel")
        self.CloudEnableIcon = QtWidgets.QLabel(self.centralwidget)
        self.CloudEnableIcon.setGeometry(QtCore.QRect(165, 15, 40, 40))
        self.CloudEnableIcon.setText("")
        self.CloudEnableIcon.setPixmap(QtGui.QPixmap(":/NotificationPanel/icons/CloudEnableIcon.png"))
        self.CloudEnableIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.CloudEnableIcon.setObjectName("CloudEnableIcon")
        self.TemperatureLabel = QtWidgets.QLabel(self.centralwidget)
        self.TemperatureLabel.setGeometry(QtCore.QRect(1180, 16, 90, 38))
        self.TemperatureLabel.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 30px;\n"
"color: rgb(255, 255, 255);")
        self.TemperatureLabel.setObjectName("TemperatureLabel")
        self.FuelBoxLabel = QtWidgets.QLabel(self.centralwidget)
        self.FuelBoxLabel.setGeometry(QtCore.QRect(1086, 15, 66, 40))
        self.FuelBoxLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 4px;")
        self.FuelBoxLabel.setText("")
        self.FuelBoxLabel.setObjectName("FuelBoxLabel")
        self.FuelBar1 = QtWidgets.QLabel(self.centralwidget)
        self.FuelBar1.setGeometry(QtCore.QRect(1088, 18, 7, 34))
        self.FuelBar1.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 2px;")
        self.FuelBar1.setText("")
        self.FuelBar1.setObjectName("FuelBar1")
        self.FuelBar2 = QtWidgets.QLabel(self.centralwidget)
        self.FuelBar2.setGeometry(QtCore.QRect(1097, 18, 7, 34))
        self.FuelBar2.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 2px;")
        self.FuelBar2.setText("")
        self.FuelBar2.setObjectName("FuelBar2")
        self.FuelBar3 = QtWidgets.QLabel(self.centralwidget)
        self.FuelBar3.setGeometry(QtCore.QRect(1106, 18, 7, 34))
        self.FuelBar3.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 2px;")
        self.FuelBar3.setText("")
        self.FuelBar3.setObjectName("FuelBar3")
        self.FuelBar4 = QtWidgets.QLabel(self.centralwidget)
        self.FuelBar4.setGeometry(QtCore.QRect(1115, 18, 7, 34))
        self.FuelBar4.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 2px;")
        self.FuelBar4.setText("")
        self.FuelBar4.setObjectName("FuelBar4")
        self.FuelBar5 = QtWidgets.QLabel(self.centralwidget)
        self.FuelBar5.setGeometry(QtCore.QRect(1124, 18, 7, 34))
        self.FuelBar5.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 2px;")
        self.FuelBar5.setText("")
        self.FuelBar5.setObjectName("FuelBar5")
        self.FuelBar6 = QtWidgets.QLabel(self.centralwidget)
        self.FuelBar6.setGeometry(QtCore.QRect(1133, 18, 7, 34))
        self.FuelBar6.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 2px;")
        self.FuelBar6.setText("")
        self.FuelBar6.setObjectName("FuelBar6")
        self.FuelBar7 = QtWidgets.QLabel(self.centralwidget)
        self.FuelBar7.setGeometry(QtCore.QRect(1142, 18, 7, 34))
        self.FuelBar7.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 2px;")
        self.FuelBar7.setText("")
        self.FuelBar7.setObjectName("FuelBar7")
        self.NetworkEnableIcon = QtWidgets.QLabel(self.centralwidget)
        self.NetworkEnableIcon.setGeometry(QtCore.QRect(1022, 15, 40, 40))
        self.NetworkEnableIcon.setText("")
        self.NetworkEnableIcon.setPixmap(QtGui.QPixmap(":/NotificationPanel/icons/NetworkEnableIcon.png"))
        self.NetworkEnableIcon.setObjectName("NetworkEnableIcon")
        self.BTOnIcon = QtWidgets.QLabel(self.centralwidget)
        self.BTOnIcon.setGeometry(QtCore.QRect(962, 15, 40, 40))
        self.BTOnIcon.setText("")
        self.BTOnIcon.setPixmap(QtGui.QPixmap(":/NotificationPanel/icons/BTOnIcon.png"))
        self.BTOnIcon.setObjectName("BTOnIcon")
        self.MainMenu = QtWidgets.QTabWidget(self.centralwidget)
        self.MainMenu.setGeometry(QtCore.QRect(0, 70, 1280, 650))
        self.MainMenu.setMinimumSize(QtCore.QSize(130, 130))
        self.MainMenu.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.MainMenu.setStyleSheet("QTabBar::tab:selected {\n"
"background-color: rgb(144, 216, 255);\n"
"\n"
"}\n"
"QTabBar::tab{\n"
"background-color: rgb(255, 255, 255);\n"
"padding:24px 0 0 0;\n"
"}")
        self.MainMenu.setTabPosition(QtWidgets.QTabWidget.East)
        self.MainMenu.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.MainMenu.setIconSize(QtCore.QSize(90, 130))
        self.MainMenu.setElideMode(QtCore.Qt.ElideMiddle)
        self.MainMenu.setTabsClosable(False)
        self.MainMenu.setObjectName("MainMenu")
        self.MusicTab = QtWidgets.QWidget()
        self.MusicTab.setObjectName("MusicTab")
        self.MusicMenu = QtWidgets.QTabWidget(self.MusicTab)
        self.MusicMenu.setGeometry(QtCore.QRect(0, 0, 1150, 650))
        self.MusicMenu.setStyleSheet("QTabBar::tab:selected {\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QTabBar::tab{\n"
"background-color: rgb(144, 216, 255);\n"
"padding:0 0 30px 0;\n"
"}")
        self.MusicMenu.setTabPosition(QtWidgets.QTabWidget.West)
        self.MusicMenu.setIconSize(QtCore.QSize(84, 130))
        self.MusicMenu.setObjectName("MusicMenu")
        self.FMTab = QtWidgets.QWidget()
        self.FMTab.setObjectName("FMTab")
        self.ChannelFrequencyLabel = QtWidgets.QLabel(self.FMTab)
        self.ChannelFrequencyLabel.setGeometry(QtCore.QRect(393, 136, 165, 91))
        self.ChannelFrequencyLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 72px;\n"
"line-height: 91px;")
        self.ChannelFrequencyLabel.setObjectName("ChannelFrequencyLabel")
        self.MegaHertzLabel = QtWidgets.QLabel(self.FMTab)
        self.MegaHertzLabel.setGeometry(QtCore.QRect(560, 150, 90, 90))
        self.MegaHertzLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 36px;\n"
"line-height: 91px;")
        self.MegaHertzLabel.setObjectName("MegaHertzLabel")
        self.FMForwardButton = QtWidgets.QPushButton(self.FMTab)
        self.FMForwardButton.setGeometry(QtCore.QRect(843, 136, 90, 110))
        self.FMForwardButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/FMForwardButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FMForwardButton.setIcon(icon)
        self.FMForwardButton.setIconSize(QtCore.QSize(40, 71))
        self.FMForwardButton.setObjectName("FMForwardButton")
        self.FMBackwardButton = QtWidgets.QPushButton(self.FMTab)
        self.FMBackwardButton.setGeometry(QtCore.QRect(137, 136, 90, 110))
        self.FMBackwardButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/FMBackwardButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FMBackwardButton.setIcon(icon1)
        self.FMBackwardButton.setIconSize(QtCore.QSize(40, 71))
        self.FMBackwardButton.setObjectName("FMBackwardButton")
        self.Channel1Button = QtWidgets.QPushButton(self.FMTab)
        self.Channel1Button.setGeometry(QtCore.QRect(100, 320, 140, 140))
        self.Channel1Button.setStyleSheet("border:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 48px;\n"
"line-height: 60px;")
        self.Channel1Button.setObjectName("Channel1Button")
        self.Channel2Button = QtWidgets.QPushButton(self.FMTab)
        self.Channel2Button.setGeometry(QtCore.QRect(270, 320, 140, 140))
        self.Channel2Button.setStyleSheet("border:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 48px;\n"
"line-height: 60px;")
        self.Channel2Button.setObjectName("Channel2Button")
        self.Channel3Button = QtWidgets.QPushButton(self.FMTab)
        self.Channel3Button.setGeometry(QtCore.QRect(440, 320, 140, 140))
        self.Channel3Button.setStyleSheet("border:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 48px;\n"
"line-height: 60px;")
        self.Channel3Button.setObjectName("Channel3Button")
        self.Channel4Button = QtWidgets.QPushButton(self.FMTab)
        self.Channel4Button.setGeometry(QtCore.QRect(610, 320, 140, 140))
        self.Channel4Button.setStyleSheet("border:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 48px;\n"
"line-height: 60px;")
        self.Channel4Button.setObjectName("Channel4Button")
        self.Channel5Button = QtWidgets.QPushButton(self.FMTab)
        self.Channel5Button.setGeometry(QtCore.QRect(780, 320, 140, 140))
        self.Channel5Button.setStyleSheet("border:1px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 48px;\n"
"line-height: 60px;")
        self.Channel5Button.setObjectName("Channel5Button")
        self.FMControlPanelBox = QtWidgets.QLabel(self.FMTab)
        self.FMControlPanelBox.setGeometry(QtCore.QRect(0, 550, 1020, 100))
        self.FMControlPanelBox.setStyleSheet("border-top:1px solid rgb(255, 255, 255);")
        self.FMControlPanelBox.setObjectName("FMControlPanelBox")
        self.BandFMButton = QtWidgets.QPushButton(self.FMTab)
        self.BandFMButton.setGeometry(QtCore.QRect(330, 552, 120, 100))
        self.BandFMButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/BandFMIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BandFMButton.setIcon(icon2)
        self.BandFMButton.setIconSize(QtCore.QSize(46, 51))
        self.BandFMButton.setObjectName("BandFMButton")
        self.FMcontrolLine1 = QtWidgets.QFrame(self.FMTab)
        self.FMcontrolLine1.setGeometry(QtCore.QRect(450, 575, 1, 50))
        self.FMcontrolLine1.setStyleSheet("color: rgb(255, 255, 255);")
        self.FMcontrolLine1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FMcontrolLine1.setFrameShape(QtWidgets.QFrame.VLine)
        self.FMcontrolLine1.setObjectName("FMcontrolLine1")
        self.BandFMStationButton = QtWidgets.QPushButton(self.FMTab)
        self.BandFMStationButton.setGeometry(QtCore.QRect(451, 552, 118, 100))
        self.BandFMStationButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/StationFMIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BandFMStationButton.setIcon(icon3)
        self.BandFMStationButton.setIconSize(QtCore.QSize(63, 47))
        self.BandFMStationButton.setObjectName("BandFMStationButton")
        self.FMControlLine2 = QtWidgets.QFrame(self.FMTab)
        self.FMControlLine2.setGeometry(QtCore.QRect(570, 575, 1, 50))
        self.FMControlLine2.setStyleSheet("color: rgb(255, 255, 255);")
        self.FMControlLine2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FMControlLine2.setFrameShape(QtWidgets.QFrame.VLine)
        self.FMControlLine2.setObjectName("FMControlLine2")
        self.TuneFMButton = QtWidgets.QPushButton(self.FMTab)
        self.TuneFMButton.setGeometry(QtCore.QRect(571, 552, 120, 100))
        self.TuneFMButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/TuneFMIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TuneFMButton.setIcon(icon4)
        self.TuneFMButton.setIconSize(QtCore.QSize(41, 47))
        self.TuneFMButton.setObjectName("TuneFMButton")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/FMTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MusicMenu.addTab(self.FMTab, icon5, "")
        self.BTTab = QtWidgets.QWidget()
        self.BTTab.setObjectName("BTTab")
        self.BTControlPanelBox = QtWidgets.QLabel(self.BTTab)
        self.BTControlPanelBox.setGeometry(QtCore.QRect(0, 550, 1020, 100))
        self.BTControlPanelBox.setStyleSheet("border-top:1px solid rgb(255, 255, 255);")
        self.BTControlPanelBox.setText("")
        self.BTControlPanelBox.setObjectName("BTControlPanelBox")
        self.PreviousSongBTButton = QtWidgets.QPushButton(self.BTTab)
        self.PreviousSongBTButton.setGeometry(QtCore.QRect(360, 552, 100, 100))
        self.PreviousSongBTButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/PreviousSongButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PreviousSongBTButton.setIcon(icon6)
        self.PreviousSongBTButton.setIconSize(QtCore.QSize(40, 40))
        self.PreviousSongBTButton.setObjectName("PreviousSongBTButton")
        self.BTcontrolLine1 = QtWidgets.QFrame(self.BTTab)
        self.BTcontrolLine1.setGeometry(QtCore.QRect(461, 575, 1, 50))
        self.BTcontrolLine1.setStyleSheet("color: rgb(255, 255, 255);")
        self.BTcontrolLine1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.BTcontrolLine1.setFrameShape(QtWidgets.QFrame.VLine)
        self.BTcontrolLine1.setObjectName("BTcontrolLine1")
        self.PlaySongBTButton = QtWidgets.QPushButton(self.BTTab)
        self.PlaySongBTButton.setGeometry(QtCore.QRect(462, 552, 98, 100))
        self.PlaySongBTButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/PlayButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PlaySongBTButton.setIcon(icon7)
        self.PlaySongBTButton.setIconSize(QtCore.QSize(40, 40))
        self.PlaySongBTButton.setObjectName("PlaySongBTButton")
        self.BTcontrolLine2 = QtWidgets.QFrame(self.BTTab)
        self.BTcontrolLine2.setGeometry(QtCore.QRect(560, 575, 1, 50))
        self.BTcontrolLine2.setStyleSheet("color: rgb(255, 255, 255);")
        self.BTcontrolLine2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.BTcontrolLine2.setFrameShape(QtWidgets.QFrame.VLine)
        self.BTcontrolLine2.setObjectName("BTcontrolLine2")
        self.NextSongBTButton = QtWidgets.QPushButton(self.BTTab)
        self.NextSongBTButton.setGeometry(QtCore.QRect(561, 552, 100, 100))
        self.NextSongBTButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/NextSongButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextSongBTButton.setIcon(icon8)
        self.NextSongBTButton.setIconSize(QtCore.QSize(40, 40))
        self.NextSongBTButton.setObjectName("NextSongBTButton")
        self.PlayerIconBT = QtWidgets.QLabel(self.BTTab)
        self.PlayerIconBT.setGeometry(QtCore.QRect(410, 65, 200, 200))
        self.PlayerIconBT.setText("")
        self.PlayerIconBT.setPixmap(QtGui.QPixmap(":/NotificationPanel/icons/PlayerIcon.png"))
        self.PlayerIconBT.setObjectName("PlayerIconBT")
        self.SongNameBTLabel = QtWidgets.QLabel(self.BTTab)
        self.SongNameBTLabel.setGeometry(QtCore.QRect(260, 310, 500, 45))
        self.SongNameBTLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 36px;\n"
"line-height: 45px;\n"
"text-align: center;")
        self.SongNameBTLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.SongNameBTLabel.setObjectName("SongNameBTLabel")
        self.AlbumNameBTLabel = QtWidgets.QLabel(self.BTTab)
        self.AlbumNameBTLabel.setGeometry(QtCore.QRect(260, 365, 500, 45))
        self.AlbumNameBTLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 36px;\n"
"line-height: 45px;\n"
"text-align: center;")
        self.AlbumNameBTLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.AlbumNameBTLabel.setObjectName("AlbumNameBTLabel")
        self.ArtistNameBTLabel = QtWidgets.QLabel(self.BTTab)
        self.ArtistNameBTLabel.setGeometry(QtCore.QRect(260, 420, 500, 45))
        self.ArtistNameBTLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 36px;\n"
"line-height: 45px;\n"
"text-align: center;")
        self.ArtistNameBTLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.ArtistNameBTLabel.setObjectName("ArtistNameBTLabel")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/BTTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MusicMenu.addTab(self.BTTab, icon9, "")
        self.USBTab = QtWidgets.QWidget()
        self.USBTab.setObjectName("USBTab")
        self.ReloadUSBButton = QtWidgets.QPushButton(self.USBTab)
        self.ReloadUSBButton.setGeometry(QtCore.QRect(0, 0, 400, 60))
        self.ReloadUSBButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:2px solid rgb(144,216,255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 24px;\n"
"line-height: 23px;\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/ReloadUSBButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ReloadUSBButton.setIcon(icon10)
        self.ReloadUSBButton.setObjectName("ReloadUSBButton")
        #added song function AddSongUSB
        self.ReloadUSBButton.clicked.connect(self.AddSongUSB)
        self.SongListBox = QtWidgets.QListWidget(self.USBTab)
        self.SongListBox.setGeometry(QtCore.QRect(0, 60, 400, 490))
        self.SongListBox.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"color: rgb(255, 255, 255);\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 20px;\n"
"line-height: 23px;")
        self.SongListBox.setTextElideMode(QtCore.Qt.ElideLeft)
        self.SongListBox.setObjectName("SongListBox")
        #adding double click function to play song
        self.SongListBox.itemDoubleClicked.connect(self.PlaySongFromListUSB)
        self.USBControlPanelBox = QtWidgets.QLabel(self.USBTab)
        self.USBControlPanelBox.setGeometry(QtCore.QRect(0, 550, 1020, 100))
        self.USBControlPanelBox.setStyleSheet("border-top:1px solid rgb(255, 255, 255);")
        self.USBControlPanelBox.setText("")
        self.USBControlPanelBox.setObjectName("USBControlPanelBox")
        self.PlayerIcon = QtWidgets.QLabel(self.USBTab)
        self.PlayerIcon.setGeometry(QtCore.QRect(610, 70, 200, 200))
        self.PlayerIcon.setText("")
        self.PlayerIcon.setPixmap(QtGui.QPixmap(":/NotificationPanel/icons/PlayerIcon.png"))
        self.PlayerIcon.setObjectName("PlayerIcon")
        self.SongNameUSBLabel = QtWidgets.QLabel(self.USBTab)
        self.SongNameUSBLabel.setGeometry(QtCore.QRect(485, 305, 450, 45))
        self.SongNameUSBLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 36px;\n"
"line-height: 45px;\n"
"text-align: center;")
        self.SongNameUSBLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.SongNameUSBLabel.setObjectName("SongNameUSBLabel")
        self.ProgressBarUSB = QtWidgets.QProgressBar(self.USBTab)
        self.ProgressBarUSB.setGeometry(QtCore.QRect(550, 430, 320, 5))
        self.ProgressBarUSB.setStyleSheet("QProgressBar::chunk {\n"
"    background-color: rgb(144,216,255);\n"
"}")
        self.ProgressBarUSB.setProperty("value", 24)
        self.ProgressBarUSB.setTextVisible(False)
        self.ProgressBarUSB.setObjectName("ProgressBarUSB")
        self.SongCurrentTimeLabel = QtWidgets.QLabel(self.USBTab)
        self.SongCurrentTimeLabel.setGeometry(QtCore.QRect(470, 420, 60, 25))
        self.SongCurrentTimeLabel.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"line-height: 23px;\n"
"color: rgb(255, 255, 255);")
        self.SongCurrentTimeLabel.setObjectName("SongCurrentTimeLabel")
        self.SongTotalTimeLabel = QtWidgets.QLabel(self.USBTab)
        self.SongTotalTimeLabel.setGeometry(QtCore.QRect(890, 420, 60, 25))
        self.SongTotalTimeLabel.setStyleSheet("font-family: Plus Jakarta Sans;\n"
"font-style: normal;\n"
"font-weight: 500;\n"
"font-size: 18px;\n"
"line-height: 23px;\n"
"color: rgb(255, 255, 255);")
        self.SongTotalTimeLabel.setObjectName("SongTotalTimeLabel")
        self.PreviousSongUSBButton = QtWidgets.QPushButton(self.USBTab)
        self.PreviousSongUSBButton.setGeometry(QtCore.QRect(360, 552, 100, 100))
        self.PreviousSongUSBButton.setText("")
        self.PreviousSongUSBButton.setIcon(icon6)
        self.PreviousSongUSBButton.setIconSize(QtCore.QSize(40, 40))
        self.PreviousSongUSBButton.setObjectName("PreviousSongUSBButton")
        #added function PreviousSongUSB
        self.PreviousSongUSBButton.clicked.connect(self.PreviousSongUSB)
        self.USBcontrolLine1 = QtWidgets.QFrame(self.USBTab)
        self.USBcontrolLine1.setGeometry(QtCore.QRect(461, 575, 1, 50))
        self.USBcontrolLine1.setStyleSheet("color: rgb(255, 255, 255);")
        self.USBcontrolLine1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.USBcontrolLine1.setFrameShape(QtWidgets.QFrame.VLine)
        self.USBcontrolLine1.setObjectName("USBcontrolLine1")
        self.PlaySongUSBButton = QtWidgets.QPushButton(self.USBTab)
        self.PlaySongUSBButton.setGeometry(QtCore.QRect(462, 552, 98, 100))
        self.PlaySongUSBButton.setText("")
        self.PlaySongUSBButton.setIcon(icon7)
        self.PlaySongUSBButton.setIconSize(QtCore.QSize(40, 40))
        self.PlaySongUSBButton.setObjectName("PlaySongUSBButton")
        #added function PlaySongUSB
        self.PlaySongUSBButton.clicked.connect(self.PlaySongUSB)
        self.USBcontrolLine2 = QtWidgets.QFrame(self.USBTab)
        self.USBcontrolLine2.setGeometry(QtCore.QRect(560, 575, 1, 50))
        self.USBcontrolLine2.setStyleSheet("color: rgb(255, 255, 255);")
        self.USBcontrolLine2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.USBcontrolLine2.setFrameShape(QtWidgets.QFrame.VLine)
        self.USBcontrolLine2.setObjectName("USBcontrolLine2")
        self.NextSongUSBButton = QtWidgets.QPushButton(self.USBTab)
        self.NextSongUSBButton.setGeometry(QtCore.QRect(561, 552, 100, 100))
        self.NextSongUSBButton.setText("")
        self.NextSongUSBButton.setIcon(icon8)
        self.NextSongUSBButton.setIconSize(QtCore.QSize(40, 40))
        self.NextSongUSBButton.setObjectName("NextSongUSBButton")
        #added function NextSongUSB
        self.NextSongUSBButton.clicked.connect(self.NextSongUSB)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/USBTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MusicMenu.addTab(self.USBTab, icon11, "")
        self.AuxTab = QtWidgets.QWidget()
        self.AuxTab.setObjectName("AuxTab")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/AuxTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MusicMenu.addTab(self.AuxTab, icon12, "")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/MusicTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainMenu.addTab(self.MusicTab, icon13, "")
        self.PhoneTab = QtWidgets.QWidget()
        self.PhoneTab.setObjectName("PhoneTab")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/PhoneTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainMenu.addTab(self.PhoneTab, icon14, "")
        self.CameraTab = QtWidgets.QWidget()
        self.CameraTab.setObjectName("CameraTab")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/CameraTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainMenu.addTab(self.CameraTab, icon15, "")
        self.StatusTab = QtWidgets.QWidget()
        self.StatusTab.setObjectName("StatusTab")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/StatusTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainMenu.addTab(self.StatusTab, icon16, "")
        self.ParkingTab = QtWidgets.QWidget()
        self.ParkingTab.setObjectName("ParkingTab")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/NotificationPanel/icons/ParkingTabIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainMenu.addTab(self.ParkingTab, icon17, "")
        self.timer = QTimer()
        self.timer.setInterval(1000)
        self.timer.timeout.connect(self.updateprogressbar)       
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.MainMenu.setCurrentIndex(0)
        self.MusicMenu.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NotificationPanel.setText(_translate("MainWindow", "TextLabel"))
        self.TimeLabel.setText(_translate("MainWindow", "10:20 AM"))
        self.TemperatureLabel.setText(_translate("MainWindow", "<html><head/><body><p>25°C</p></body></html>"))
        self.ChannelFrequencyLabel.setText(_translate("MainWindow", "93.5"))
        self.MegaHertzLabel.setText(_translate("MainWindow", "MHz"))
        self.Channel1Button.setText(_translate("MainWindow", "1"))
        self.Channel2Button.setText(_translate("MainWindow", "2"))
        self.Channel3Button.setText(_translate("MainWindow", "3"))
        self.Channel4Button.setText(_translate("MainWindow", "4"))
        self.Channel5Button.setText(_translate("MainWindow", "5"))
        self.FMControlPanelBox.setText(_translate("MainWindow", "TextLabel"))
        self.SongNameBTLabel.setText(_translate("MainWindow", "Sakhiyan 2.0-Bell Bottom 2021"))
        self.AlbumNameBTLabel.setText(_translate("MainWindow", "Saregama Music"))
        self.ArtistNameBTLabel.setText(_translate("MainWindow", "Arijit Singh & Pritam"))
        self.ReloadUSBButton.setText(_translate("MainWindow", "  Reload Songs"))
        self.SongNameUSBLabel.setText(_translate("MainWindow", "Sakhiyan 2.0-Bell Bottom 2021"))
        self.SongCurrentTimeLabel.setText(_translate("MainWindow", "00:00"))
        self.SongTotalTimeLabel.setText(_translate("MainWindow", "00:00"))

    def AddSongUSB(self):
        dir_path = os.path.dirname("F:/")
        i=0
        for root, dirs, files in os.walk(dir_path):
            for file in files: 
                if file.endswith('.mp3'):
                    i = i+1
                    directory=os.path.join(root, file)
                    musiclist.append(directory)
                    self.SongListBox.addItem(file)
        if i==0:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("No Songs in USB")
                msg.setWindowTitle("No Songs")
                msg.exec_()

    def PlaySongFromListUSB(self):
        global play,current_song,songLength,count,index
        count = 0
        index = self.SongListBox.currentRow()      
        try:
            mixer.music.load(str(musiclist[index]))
            mixer.music.play()
            play =True
            current_song = index
            song_name=musiclist[index]
            song_name=song_name.split("\\")
            song_name=song_name[-1]
            song_name=song_name.split(".")
            self.SongNameUSBLabel.setText(song_name[0])
            self.timer.start()
            sound = MP3(str(musiclist[index]))
            songLength = sound.info.length
            songLength =round(songLength)
            min,sec=divmod(songLength,60)
            #Total song length
            length=str(min)+":"+str(sec)
            self.SongTotalTimeLabel.setText(length)
        except:
            pass
    def PlaySongUSB(self):
        global play,current_song,songLength,count,index
        index = self.SongListBox.currentRow()
        
        if play == False:
            if current_song == index:
                
                play = True
                self.timer.start()
                mixer.music.unpause()

            else:   
                try:
                    count = 0
                    mixer.music.load(musiclist[index])
                    song_name=musiclist[index]
                    song_name=song_name.split("\\")
                    song_name=song_name[-1]
                    song_name=song_name.split(".")
                    self.SongNameUSBLabel.setText(song_name[0])
                    mixer.music.play()
                    current_song = index
                    self.timer.start()
                    sound = MP3(str(musiclist[index]))
                    songLength = sound.info.length
                    songLength =round(songLength)
                    min,sec=divmod(songLength,60)
                    #Total song length
                    length=str(min)+":"+str(sec)
                    self.SongTotalTimeLabel.setText(length)
                except:
                    pass 
            play = True        
        elif play ==True:
            play = False
            self.timer.stop()
            mixer.music.pause()
    def PreviousSongUSB(self):
        global play,current_song,songLength,count,index
        if index ==0:
            index = len(musiclist)-1
        else:
            index-=1    
        try:
            count = 0
            mixer.music.load(musiclist[index])
            mixer.music.play()
            current_song = index
            self.timer.start()
            sound = MP3(str(musiclist[index]))
            songLength = sound.info.length
            songLength =round(songLength)
            min,sec=divmod(songLength,60)
            song_name=musiclist[index]
            song_name=song_name.split("\\")
            song_name=song_name[-1]
            song_name=song_name.split(".")
            self.SongNameUSBLabel.setText(song_name[0])
            #Total song length
            length=str(min)+":"+str(sec)
            self.SongTotalTimeLabel.setText(length)

         
        except:
            pass
    def NextSongUSB(self):
        global play,current_song,songLength,count,index
        if index ==len(musiclist)-1:
            index = 0
        else:
            index+=1    
        try:
            count = 0
            mixer.music.load(musiclist[index])
            mixer.music.play()
            current_song = index
            self.timer.start()
            sound = MP3(str(musiclist[index]))
            songLength = sound.info.length
            songLength =round(songLength)
            min,sec=divmod(songLength,60)
            song_name=musiclist[index]
            song_name=song_name.split("\\")
            song_name=song_name[-1]
            song_name=song_name.split(".")
            self.SongNameUSBLabel.setText(song_name[0])
            #Total song length
            length=str(min)+":"+str(sec)
            self.SongTotalTimeLabel.setText(length)            
        except:
            pass
    def updateprogressbar(self):
        global count,songLength
        count +=1
        self.ProgressBarUSB.setValue(count)
        self.SongCurrentTimeLabel.setText("%02d:%02d"%(count/60,count%60))
       
        if count == songLength:
            self.timer.stop()
            self.NextSongUSB()
    
      




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()
    sys.exit(app.exec_())
